In [1]:
import numpy as np

## 1) Write a program to create a 5 dimensional array with all zeros and ones

In [41]:
zero=np.array([[0,0,0],[0,0,0],[0,0,0]],ndmin=5)
ones=np.array([[1,1,1],[1,1,1],[1,1,1]],ndmin=5)
print(zero,'\n')
print(ones)

[[[[[0 0 0]
    [0 0 0]
    [0 0 0]]]]] 

[[[[[1 1 1]
    [1 1 1]
    [1 1 1]]]]]


## 2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [33]:
z1=np.zeros((3,10))
z2=np.ones((3,10))
z3=np.array([[5,5,5,5,5,5,5,5,5,5],[5,5,5,5,5,5,5,5,5,5],[5,5,5,5,5,5,5,5,5,5]])
print(z1.astype(int),'\n')
print(z2.astype(int),'\n')
print(z3)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]] 

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


## 3) Write a program to create a 3x4 matrix filled with values from 10 to 21

In [35]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## 4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9, 

In [42]:
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

## 5) Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.
    

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16



In [72]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b[::,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

## 6) Write a program to reverse an array (the first element becomes the last).
Given array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [77]:
c=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])
np.flip(c,0)

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

## 7)  Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [97]:
d=np.arange(1,101).reshape(10,10)
final=[]
for i in d:
    for k in i:
        if k>30 and k<80 and k%5==0:
            final.append(k)
print(d,'\n\n')
print('Elemnts which are >30 and <80 and %5==0 are:- \n',final)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] 


Elemnts which are >30 and <80 and %5==0 are:- 
 [35, 40, 45, 50, 55, 60, 65, 70, 75]


## 8) Write a program to create a 2D array with 1 on the border and 0 inside.

In [131]:
h=np.ones((4,4),dtype=int)
h[1:3,1:3]=0
h

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

## 9) Write a program to create a checkerboard pattern .Don't use default array function Checkerboard pattern:

## 10) Write a program to find common values between two arrays.
Expected Output:
array1: [10 20 40 60]
array2: [10, 30, 40,50]

In [138]:
arr1=np.array([20,45,85,96])
arr2=np.array([15,96,85,48])
common=[]
for i in arr1:
    for i1 in arr2:
        if i==i1:
            common.append(i)
print('common elements between two arrays is\n',common)

common elements between two arrays is
 [85, 96]


## 11) Write a program to create an array 2d array and then reshape into 1d array

In [151]:
o=np.array([[1,2,3],[4,5,6],[7,8,9]])
o.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 12) Write a user defined function for creating a 1 or 2d array from scratch without using array functions